%  
%  Ex_CallMatlabFunctions  
%
%  Call an external MATLAB function from a GMAT script.
%


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;

%----------------------------------------
%---------- Arrays, Variables, Strings
%----------------------------------------

Create Array vec[4,1];
Create Variable maxVec floorValue isAField fieldValue;
Create String fieldName
vec(1, 1) = 1;
vec(2, 1) = 2;
vec(3, 1) = 3;
vec(4, 1) = 4.2214331;
fieldName = 'CoordinateSystem';

%----------------------------------------
%---------- Functions
%----------------------------------------

Create MatlabFunction max floor isfield getfield;
Create ReportFile rf;

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;

[maxVec] = max(vec);
Report rf maxVec;

[floorValue] = floor(maxVec);
Report rf floorValue;


